# Generated by Django 3.0.6 on 2020-06-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200603_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='labels',
            field=models.CharField(blank=True, choices=[('special', 'special'), ('', 'Non Special')], max_length=300),
        ),
    ]
